### ISSUE TITLE
Need to remove [Coming Soon] on Vault Creation

### ISSUE THREAD

**Issue by Lyskey1** [tradeparadex/paradex-docs#43]
### Documentation Page URL

https://docs.paradex.trade/documentation/vaults/vaults-introduction

### Issue Description

Since Vaults creation is now possible for everyone, need to remove coming soon here:
- An Asset Manager looking for more capital base? -> Become a Vault Operator [Coming Soon] 
- Benefits for Asset Managers (Vault Owners) [Coming Soon]

**Comment by ClemMakesApps** [comment]
Thanks! Resolved by https://github.com/tradeparadex/paradex-docs/pull/51
