### ISSUE TITLE
Link issue on this page

### ISSUE THREAD

**Issue by Lyskey1** [tradeparadex/paradex-docs#45]
### Documentation Page URL

https://docs.paradex.trade/documentation/getting-started/architecture-overview/bridges-and-audits

### Issue Description

The following link redirection doesn't work on my end: [Starknet Core Summary Report](https://docs.paradex.trade/assets/Starknet%20Core%20Summary%20Report%20-%20Sept%202022.pdf)

I get an error 404: This page could not be found.

### Steps to Reproduce (Optional)

1. Go to the page https://docs.paradex.trade/documentation/getting-started/architecture-overview/bridges-and-audits
2. Click on the link presented here: [Starknet Core Summary Report]
3. Observe the redirection issue

**Comment by ClemMakesApps** [comment]
@pentaczek666 Here's the original linked doc from gitbook: https://files.gitbook.com/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FV7pCNj9LRpZgf4HgACVM%2Fuploads%2Fgit-blob-103918da7c89f9f5bda345af0ca519f3a1c3c966%2FStarknet%20Core%20Summary%20Report%20-%20Sept%202022.pdf?alt=media

**Comment by aweaver89** [comment]
Just updated and should be good now @Lyskey1 !!!

Thanks for pointing this out!
