### ISSUE TITLE
I think you forgot to include some links.

### ISSUE THREAD

**Issue by Lyskey1** [tradeparadex/paradex-docs#46]
### Documentation Page URL

https://docs.paradex.trade/documentation/getting-started/architecture-overview/starknet-first-appchain

### Issue Description

From my understanding of this page, the following sections should include links to direct people to more information about each concept.

_You can learn more about the following topics:
StarkWare
Starknet
Rollups
ZK-Rollups
STARKs, SNARKs and Validity Proofs
Fractal Scaling - App-chains in Rollups_

**Comment by ClemMakesApps** [comment]
Thanks @Lyskey1 for the suggestion! We'll discuss and see what links would be good to add here to make it more accessible for readers to learn more about those topics

**Comment by pentaczek666** [comment]
* [StarkWare](https://starkware.co/)
* [Starknet](https://www.starknet.io/)
* [Rollups](https://www.coinbase.com/en-gb/learn/wallet/what-are-rollups-in-crypto)
* [ZK-Rollups](https://ethereum.org/en/developers/docs/scaling/zk-rollups/)
* [STARKs, SNARKs and Validity Proofs](https://consensys.io/blog/zero-knowledge-proofs-starks-vs-snarks)
* [Fractal Scaling - App-chains in Rollups](https://ethresear.ch/t/fractal-scaling-on-ethereum-layer-3-rollups/19022)


Original documentation also had no links to the resources, so list of proposed links is attached. For the time being docs are populated with these
