### ISSUE TITLE
Documentation error in Funding Period example - incorrect intrinsic value and calculation

### ISSUE THREAD

**Issue by 0xmakerr** [tradeparadex/paradex-docs#95]
### Documentation Page URL

https://docs.paradex.trade/documentation/perpetual-options/funding-mechanism

### Issue Description

Incorrect strike/intrinsic value: With spot price $100,000 and strike $99,000, BTC-USD-99000-C is in-the-money with $1,000 intrinsic value. Currently incorrectly states it's "out-of-money" with "zero intrinsic value".

Calculation error: Claims "-5 * (500 * 1/8) = $312.5" which should be "-$312.5".

### Suggested Improvement

change the example in the docs to:

Example:
Spot Price = $100,000
1 USDC = 1 USD
Funding Period = 8 hours

BTC-USD-101000-C has a price of $500. Since the option is out-of-money (i.e. zero intrinsic value), the time value is also $500. This corresponds to a Funding Premium of 500 USDC.

If Alice buys 5 BTC-USD-99000-C. After 1 hour and if market prices are unchanged, Alice will have a Funding PnL of -5 * (500 * 1 / 8) = -$312.5

**Comment by 0xmakerr** [comment]
Also the "After 1 hour and if market prices are unchanged, Alice will have a Funding PnL of -5 * (500 * 1 / 8) = $312.5" should have negative PNL like this "After 1 hour and if market prices are unchanged, Alice will have a Funding PnL of -5 * (500 * 1 / 8) = -$312.5"

**Comment by salmon258** [comment]
Hey @0xmakerr  thank you for spotting this!
We have updated the strikes to 101000 to better represent OTM example

cheers
